import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skill from "../components/Skill";
import WorkExperience from "../components/WorkExperience";
import { Experience, PageInfo, Project, Social } from "../typings";
import { fetchExperiences } from "../utils/fetchExperiences";
// import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchProject } from "../utils/fetchProject";
import { fetchSocial } from "../utils/fetchSocial";

type Props = {
  // pageInfo: PageInfo;
  experiences: Experience[];
  projects: Project[];
  socials: Social[];
};

const Home = ({ experiences, projects, socials }: Props) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]">
      <Head>
        <title>Fikris Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />

      {/* Hero */}
      {/* <section id="hero" className="snap-start">
        <Hero pageInfo={pageInfo} />
      </section> */}

      {/* About */}
      {/* <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section> */}

      {/* Experience */}
      <section id="experience" className="snap-center">
        <WorkExperience experiences={experiences} />
      </section>

      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skill />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>

      {/* Contact Me  */}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  // const pageInfo: PageInfo = await fetchPageInfo();
  const experiences: Experience[] = await fetchExperiences();
  const projects: Project[] = await fetchProject();
  const socials: Social[] = await fetchSocial();

  return {
    props: {
      // pageInfo,
      experiences,
      projects,
      socials,
    },
    // Next.js will attempt to re-generate the page;
    // ~ When a request comes in
    // ~ At most once every 10 seconds
    revalidate: 10,
  };
};
